version: "3.7"

services:
  jspedsrest:
    build:
      context: . 
    command: python manage.py runserver 0.0.0.0:8090
    volumes:
      - ./jspedsRest:/jspedsRest
    ports:
      - 8090:8090
    env_file:
      - ./.env.dev
    networks:
      - tunnel
   
  cloudflaretunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    restart: unless-stopped
    entrypoint: ["cloudflared", "tunnel", "--no-autoupdate", "run", "--token", "$CLOUDFLARE_TUNNEL_TOKEN"]
    networks:
      - tunnel

networks:
  tunnel: