# Generated by Django 4.1.7 on 2023-03-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jspeds', '0003_remove_application_app_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSerializer',
        ),
        migrations.AddField(
            model_name='application',
            name='app_status',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='app_status_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='app_type',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='applicant_ref',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='art_unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assignee',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='assignment',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='conf_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='content',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='continuing_app',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='entity_category',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='examiner',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='file_loc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='filing_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='first_inventor',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='fitf',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='grant_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='inventors',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ipOfficeCode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='law_firm_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='law_firms',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nationalClass',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='nationalSubclass',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='patent_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='peds_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='practitioners',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pros_hist',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pta_amount',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='pta_bag',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='publication_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='related_for',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='terminal_disclaimer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
