# Generated by Django 4.1.7 on 2023-03-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jspeds', '0004_delete_appserializer_application_app_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatAppCrossRef',
            fields=[
                ('app_no', models.CharField(db_column='app_no', max_length=30, primary_key=True, serialize=False)),
                ('publication_number', models.CharField(max_length=30, null=True)),
                ('publication_date', models.DateField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='fitf',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
