# Generated by Django 4.1.7 on 2023-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jspeds', '0005_patappcrossref_alter_application_fitf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patappcrossref',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='patappcrossref',
            name='patent_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
